import fs from 'node:fs';
const read = (p) => fs.readFileSync(p, 'utf8');
const home = read('dist/index.html');
const evaluation = read('dist/evaluacion/index.html');
const contacto = read('dist/contacto/index.html');
const version = JSON.parse(read('dist/version.json'));
const vercel = JSON.parse(read('vercel.json'));
const campaign = read('src/config/campaignLinks.ts');
const pkg = read('package-lock.json');
const css = read('src/styles/global.css');
const layout = read('src/layouts/Layout.astro');
const favicon = read('public/favicon.svg').toLowerCase();
const og = read('public/og-image.svg').toLowerCase();
const brand = read('public/brand-y.svg').toLowerCase();
const activeSource = fs.readdirSync('src/components').filter(name => name.endsWith('.astro')).map(name => read(`src/components/${name}`)).join('\n') + read('src/pages/index.astro') + read('src/pages/evaluacion.astro');
const assert = (ok, message) => { if (!ok) throw new Error(message); };
assert(home.includes('<title>Sitios y sistemas web con investigación cualitativa | yassergandhi.dev</title>'), 'title exacto');
assert(home.includes('Reconstruyo cómo llega una persona, qué espera y dónde pierde continuidad. Después decidimos si conviene cambiar una página, construir un sistema o no construir todavía.'), 'description exacta');
assert((home.match(/<h1[ >]/g)||[]).length === 1, 'un H1 home');
assert((evaluation.match(/<h1[ >]/g)||[]).length === 1, 'un H1 evaluación');
assert(home.includes('rel="canonical" href="https://yassergandhi.dev/"'), 'canonical');
assert(evaluation.includes('noindex, follow'), 'noindex evaluación');
assert((evaluation.match(/<iframe/g)||[]).length === 1 && evaluation.includes('MeQjR0'), 'Tally');
assert(home.includes('https://huhugerman.com/investigacion'), 'investigación');
for (const pattern of [/\$24,999/i,/24,999/i,/24999/i,/Find where your users stop acting/i,/support absorbs the cost/i,/>SaaS</i,/SplitText/i,/ScrollTrigger/i,/\bGSAP\b/i]) assert(!pattern.test(home+evaluation), `prohibido ${pattern}`);
assert(!pkg.includes('node_modules/gsap'), 'GSAP ausente');
assert(campaign.includes('utm_content=tarjeta&offer=evaluacion_inicial') && campaign.includes('utm_content=flyer&offer=evaluacion_inicial'), 'UTM');
assert(vercel.redirects.some(r => r.source === '/contacto' && r.destination === '/evaluacion' && r.permanent), 'redirect');
assert(contacto.includes('originPage') && version.productVersion === 'north-star-v7' && version.commit, 'version');
assert(read('dist/sitemap-0.xml').includes('https://yassergandhi.dev/'), 'sitemap');
assert(fs.existsSync('public/brand-y.svg') && brand.includes('#d2e659'), 'isotipo Y');
assert(favicon.includes('#141314') && favicon.includes('#d2e659'), 'favicon V8');
assert(og.includes('#141314') && og.includes('#d2e659') && og.includes('#eeeded'), 'OG V8');
for (const color of ['#170411','#300a24','#3b1230','#e95420','#ff7a3d']) assert(!css.toLowerCase().includes(color) && !og.includes(color) && !favicon.includes(color), `color legacy ${color}`);
assert(layout.includes('Barlow+Condensed') && layout.includes('Instrument+Sans'), 'tipografías V8');
assert((layout.match(/family=/g)||[]).length === 2, 'máximo dos familias');
assert(home.includes('authorial-signature') && home.includes('huhuGERMAN'), 'firma autoral');
assert(home.includes('Primero comprendo el problema de negocio.') && home.includes('Después decidimos qué hace falta construir.'), 'frase tarjeta');
assert(home.includes('Antes de cambiar tu página, hay que entender qué está pasando con las personas que ya llegan.'), 'H1 V7');
assert(!/\$24,999|24,999|24999/i.test(activeSource), 'precio ausente en código activo');
console.log('quality V8: OK');
