import fs from 'node:fs';
const read = (p) => fs.readFileSync(p, 'utf8');
const home = read('dist/index.html');
const evaluation = read('dist/evaluacion/index.html');
const contacto = read('dist/contacto/index.html');
const version = JSON.parse(read('dist/version.json'));
const vercel = JSON.parse(read('vercel.json'));
const campaign = read('src/config/campaignLinks.ts');
const pkg = read('package-lock.json');
const assert = (ok, message) => { if (!ok) throw new Error(message); };
assert(home.includes('<title>Sitios y sistemas web con investigación cualitativa | yassergandhi.dev</title>'), 'title exacto');
assert(home.includes('Reconstruyo cómo llega una persona, qué espera y dónde pierde continuidad. Después decidimos si conviene cambiar una página, construir un sistema o no construir todavía.'), 'description exacta');
assert((home.match(/<h1[ >]/g)||[]).length === 1, 'un H1 home');
assert((evaluation.match(/<h1[ >]/g)||[]).length === 1, 'un H1 evaluación');
assert(home.includes('rel="canonical" href="https://yassergandhi.dev/"'), 'canonical');
assert(evaluation.includes('noindex, follow'), 'noindex evaluación');
assert((evaluation.match(/<iframe/g)||[]).length === 1 && evaluation.includes('MeQjR0'), 'Tally');
assert(home.includes('https://huhugerman.com/investigacion'), 'investigación');
for (const pattern of [/\$24,999/i,/24,999/i,/24999/i,/Find where your users stop acting/i,/support absorbs the cost/i,/>SaaS</i,/SplitText/i,/ScrollTrigger/i,/\bGSAP\b/i]) assert(!pattern.test(home+evaluation), `prohibido ${pattern}`);
assert(!pkg.includes('node_modules/gsap'), 'GSAP ausente');
assert(campaign.includes('utm_content=tarjeta&offer=evaluacion_inicial') && campaign.includes('utm_content=flyer&offer=evaluacion_inicial'), 'UTM');
assert(vercel.redirects.some(r => r.source === '/contacto' && r.destination === '/evaluacion' && r.permanent), 'redirect');
assert(contacto.includes('originPage') && version.productVersion === 'north-star-v7' && version.commit, 'version');
assert(read('dist/sitemap-0.xml').includes('https://yassergandhi.dev/'), 'sitemap');
console.log('quality V7: OK');
